dist: xenial
sudo: false
latex: true
language: r
r: release

warnings_are_errors: false

cache:
  packages: true
  
apt_packages:
  - libgdal-dev
  - libudunits2-dev
  
git:
  depth: false
  
r_packages:
  - ggplot2
  - shiny
  - shinyAce
  - reshape2
  - rsconnect
  
script:
  - R -f deploy.R
